# Generated by Django 3.2 on 2021-05-04 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalStockQuantity', models.IntegerField()),
                ('StockName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalBalance', models.IntegerField()),
                ('DateData', models.DateTimeField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.user')),
            ],
        ),
        migrations.CreateModel(
            name='SALE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockQuantitySale', models.IntegerField()),
                ('StockPrice', models.IntegerField()),
                ('TotalRecivable', models.IntegerField()),
                ('DateData', models.DateTimeField()),
                ('stockID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.stockdata')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.user')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockQuantityPurchase', models.IntegerField()),
                ('StockPrice', models.IntegerField()),
                ('Totalpayable', models.IntegerField()),
                ('DateData', models.DateTimeField()),
                ('stockID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.stockdata')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.user')),
            ],
        ),
        migrations.CreateModel(
            name='AddRecivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateData', models.DateTimeField()),
                ('RecivableAmount', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.user')),
            ],
        ),
        migrations.CreateModel(
            name='AddPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateData', models.DateTimeField()),
                ('PayableAmount', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockSystem.user')),
            ],
        ),
    ]
