# Generated by Django 3.2 on 2021-05-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='StockPrice',
            field=models.IntegerField(default=0),
        ),
    ]
