# Generated by Django 3.2 on 2021-05-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0002_stockdata_stockprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpayable',
            name='DateData',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='addrecivable',
            name='DateData',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='DateData',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='DateData',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='DateData',
            field=models.DateField(),
        ),
    ]
