# Generated by Django 3.2 on 2021-05-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockSystem', '0003_auto_20210505_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='TotalBalance',
            field=models.IntegerField(default=0),
        ),
    ]
